import type { GenerationJob, Project, Scene } from "./types";

const now = new Date().toISOString();

export const demoProject: Project = {
  id: "prj_coffee_30s",
  ownerId: "demo-user",
  name: "TVC cà phê buổi sớm",
  brief: "Nữ barista Việt Nam pha một tách latte trong quán nhỏ, cảm giác ấm áp và cao cấp.",
  template: "KOC review sản phẩm",
  aspectRatio: "9:16",
  targetDurationSeconds: 30,
  model: "veo-3.1-lite",
  status: "generating",
  storyBible: {
    characterLock: "Nữ barista Việt Nam 28 tuổi, tóc bob đen, áo linen be, tạp dề nâu đậm.",
    productLock: "Tách sứ trắng 180 ml có viền xanh cobalt, không chữ và không logo.",
    environmentLock: "Một quán cà phê nhỏ, quầy gỗ óc chó, máy pha espresso màu đồng.",
    lightingLock: "Ánh sáng ấm lúc 7 giờ sáng luôn chiếu từ bên trái máy quay.",
    visualStyle: "Photorealistic cinematic commercial, warm film color, shallow depth of field.",
    audioDirection: "Một track nhạc xuyên suốt, room tone quán cà phê và SFX chân thực.",
    mustAvoid: ["đổi khuôn mặt", "đổi trang phục", "đổi tách", "chữ trong khung hình"],
  },
  createdAt: now,
  updatedAt: now,
};

export const demoScenes: Scene[] = [
  {
    id: "scene_01",
    projectId: demoProject.id,
    sceneIndex: 1,
    title: "Chuẩn bị hạt",
    durationSeconds: 8,
    status: "approved",
    startState: "Barista đứng cạnh máy pha, tay giữ lọ hạt cà phê.",
    action: "Cô đổ hạt vào máy xay rồi đưa tay đến nút bật.",
    endState: "Cận cảnh ngón tay chạm nút kim loại, khung hình đứng yên.",
    prompt: "Medium tracking shot of the same barista preparing coffee beans.",
    negativePrompt: "extra people, changed wardrobe, text, deformed hands",
    transition: "seamless",
    dependsOnSceneId: null,
    startFrameUri: "/demo/keyframe-00.jpg",
    endFrameUri: "/demo/keyframe-01.jpg",
    outputVideoUri: "/demo/scene-01.mp4",
    qualityScore: 94,
  },
  {
    id: "scene_02",
    projectId: demoProject.id,
    sceneIndex: 2,
    title: "Chiết xuất espresso",
    durationSeconds: 8,
    status: "generating",
    startState: "Ngón tay vẫn chạm nút máy xay từ cảnh trước.",
    action: "Máy chạy và espresso chảy vào đúng chiếc tách trắng.",
    endState: "Tách đầy hai phần ba, dòng espresso vừa dừng.",
    prompt: "Continue seamlessly from the supplied opening frame as espresso pours.",
    negativePrompt: "cup deformation, color shift, jump cut, logo",
    transition: "match_cut",
    dependsOnSceneId: "scene_01",
    startFrameUri: "/demo/keyframe-01.jpg",
    endFrameUri: "/demo/keyframe-02.jpg",
    outputVideoUri: null,
    qualityScore: null,
  },
  {
    id: "scene_03",
    projectId: demoProject.id,
    sceneIndex: 3,
    title: "Latte art",
    durationSeconds: 8,
    status: "waiting_previous",
    startState: "Chiếc tách nằm chính giữa dưới vòi espresso.",
    action: "Barista rót sữa thành hình trái tim bằng chuyển động tự nhiên.",
    endState: "Góc top-down, latte art hoàn chỉnh và tách đứng yên.",
    prompt: "Top-down transition into a precise heart-shaped latte art pour.",
    negativePrompt: "different cup, extra hands, liquid artifacts, text",
    transition: "match_cut",
    dependsOnSceneId: "scene_02",
    startFrameUri: "/demo/keyframe-02.jpg",
    endFrameUri: "/demo/keyframe-03.jpg",
    outputVideoUri: null,
    qualityScore: null,
  },
  {
    id: "scene_04",
    projectId: demoProject.id,
    sceneIndex: 4,
    title: "Hero shot",
    durationSeconds: 8,
    status: "planned",
    startState: "Tách latte ở giữa quầy, góc nhìn từ trên xuống.",
    action: "Camera hạ xuống 45 độ khi barista đẩy tách về phía trước.",
    endState: "Tách bốc hơi sắc nét, barista mỉm cười mờ phía sau.",
    prompt: "Cinematic hero shot ending on the same steaming latte cup.",
    negativePrompt: "logo, text, face drift, abrupt zoom, product mutation",
    transition: "crossfade",
    dependsOnSceneId: "scene_03",
    startFrameUri: "/demo/keyframe-03.jpg",
    endFrameUri: "/demo/keyframe-04.jpg",
    outputVideoUri: null,
    qualityScore: null,
  },
];

export const demoJobs: GenerationJob[] = demoScenes.slice(0, 3).map((scene, index) => ({
  id: `job_0${index + 1}`,
  projectId: demoProject.id,
  sceneId: scene.id,
  provider: "mock",
  providerOperationId: index === 0 ? "mock_op_done" : `mock_op_${index + 1}`,
  model: "veo-3.1-lite",
  status: index === 0 ? "done" : index === 1 ? "running" : "queued",
  progress: index === 0 ? 100 : index === 1 ? 63 : 0,
  attempt: 1,
  estimatedCostUsd: 0.4,
  errorCode: null,
  createdAt: now,
  updatedAt: now,
}));
